### ISSUE TITLE
Paul is too smelly

### ISSUE THREAD

**Issue by DanProudfoot** [birdyboy18/birdyboy18.github.io#3]
But seriously, that border hack thing doesn't work in Windows. We made a psuedo element to fix that. ish

 border: grey 20px solid;
  content: "";
  width: calc(100% - 40px);
  height: 100%;
  position: fixed;
  top: 0;
  left: 0;

**Comment by birdyboy18** [comment]
I just decided to remove the border thing, too much hassle
